In [2]:
import numpy as np

a1 = np.array([[1,2,3,],[40,50,60]]) # 2차원배열
print(a1) 
print(a1.ndim)
print(a1.shape)
print(a1.size)


[[ 1  2  3]
 [40 50 60]]
2
(2, 3)
6


In [3]:
a2 = np.arange(20).reshape(4,5) #갯수가 안맞으면 에러남

print(a2.shape)
a2

(4, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
a3 = a2.flatten() # 2차원 배열 1차원으로 돌려줌
a3[3] = 100 # 원조값을 그대로 가져옴
print(a3)
a4 = a2.ravel() #원조값을 참조해서 가지고옴
print(a4)
a4[3] = 200

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
a2 = np.arange(20).reshape(4,5)
print(a2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [5]:
# print(a2)
# print(a2.shape)
#print(a2.sum(axis = 0))
print(a2.sum(axis = 1))

[10 35 60 85]


In [29]:
print(a2)
a3 = a2.T#축변환

print(a3,a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [31]:
print(a2, a2.shape)
a3 = np.moveaxis(a2,[0],[1]) #축변환
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [49]:
# shape (3,5)의 2차원 배열로 만들기
a10 = np.arange(5,20).reshape(3,5)
print(a10)
print(a10[:,2:4])
a11 = a10[:,2:4]
print(a11.sum(axis =0)) # 축을 따라서 연산

print(np.mean(a11, axis=0))

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 7  8]
 [12 13]
 [17 18]]
[36 39]
[12. 13.]


In [65]:
a1 = np.arange(0,10).reshape(2,5)
a2 = np.arange(100,110).reshape(2,5)
print(a1)
print(a2)
a3 = np.concatenate((a1,a2),axis=1) #2차원 배열 붙이기
print(a3)
a4 = np.hstack((a1,a2)) #hstack:수평으로 붙임
print(a4)
a5 = np.vstack((a1,a2)) # vstack:수직으로
print(a5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [100 101 102 103 104]
 [105 106 107 108 109]]


In [80]:
print(a4)
a6 = np.hsplit(a4,5) # 2차원 배열(a4)을(,n) n조각으로 잘라줌
print(a6)
a7 = a4.T
# print(a7)
np.vsplit(a7,5) # 수직으로 자름

[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[array([[0, 1],
       [5, 6]]), array([[2, 3],
       [7, 8]]), array([[  4, 100],
       [  9, 105]]), array([[101, 102],
       [106, 107]]), array([[103, 104],
       [108, 109]])]


[array([[0, 5],
        [1, 6]]),
 array([[2, 7],
        [3, 8]]),
 array([[  4,   9],
        [100, 105]]),
 array([[101, 106],
        [102, 107]]),
 array([[103, 108],
        [104, 109]])]

In [84]:
a2 = np.arange(20).reshape(4,5)
print(a2)
filter1 = (a2[:,0] % 10 == 5)
print(a2[filter1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
