-- Iris Setosa  --> 0

-- Iris Versicolour --> 1

-- Iris Virginica --> 2



In [14]:
import requests
import numpy as np

x = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [26]:
raw_data=[]
for line in x.text.split('\n'):
    raw_data.append(line.split(','))
for sample in raw_data:
    if len(sample) < 1:
        continue
    for i,value in enumerate(sample[:4]):
        try:
            sample[i] = float(value)
        except:
            sample[i] = 0.0

In [27]:
print(raw_data[:3])

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [4.7, 3.2, 1.3, 0.2, 'Iris-setosa']]


In [28]:
for sample in raw_data:
        if len(sample) < 2:
            continue
        elif 'setosa' in sample[-1]:
            sample[-1] = 0.0
        elif 'versicolor' in sample[-1]:
            sample[-1] = 1.0
        elif 'virginica' in sample[-1]:
            sample[-1] = 2.0
            

In [30]:
print(raw_data[0])
print(raw_data[51])
print(raw_data[101])

[5.1, 3.5, 1.4, 0.2, 0.0]
[6.4, 3.2, 4.5, 1.5, 1.0]
[5.8, 2.7, 5.1, 1.9, 2.0]


In [32]:
print(raw_data[-3:])
print(len(raw_data))
raw_data = raw_data[:150]

[[6.5, 3.0, 5.2, 2.0, 2.0], [6.2, 3.4, 5.4, 2.3, 2.0], [5.9, 3.0, 5.1, 1.8, 2.0]]
150


In [34]:
np_data = np.array(raw_data)
np_data.shape
np_data[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

#### 기본 통계값
* 전체(150샘플)평균, 표준편차
* 품종별평균 , 표준편차

* 평균 np.mean()
* 표준편차 np.sta()

In [52]:
print(np.mean(np_data, axis = 0))
print(np.std(np_data, axis= 0))
print(np.corrcoef(np_data.T)) #상관도 

[5.84333333 3.054      3.75866667 1.19866667 1.        ]
[0.82530129 0.43214658 1.75852918 0.76061262 0.81649658]
[[ 1.         -0.10936925  0.87175416  0.81795363  0.78256123]
 [-0.10936925  1.         -0.4205161  -0.35654409 -0.4194462 ]
 [ 0.87175416 -0.4205161   1.          0.9627571   0.94904254]
 [ 0.81795363 -0.35654409  0.9627571   1.          0.95646382]
 [ 0.78256123 -0.4194462   0.94904254  0.95646382  1.        ]]


In [59]:
filter_setosa = np_data[:,-1] == 0.0
filter_versicolor = np_data[:,-1] == 1.0
filter_virginica = np_data[:,-1] == 2.0

print(np.mean(np_data[filter_setosa], axis = 0))
print(np.std(np_data[filter_setosa], axis = 0))

print(np.mean(np_data[filter_versicolor], axis=0))

[5.006 3.418 1.464 0.244 0.   ]
[0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
[5.936 2.77  4.26  1.326 1.   ]
