- 횡단보도 연장, 녹색신호시간 : 상관도.

- 자전거 횡단도 경용 비율(전체 대비)

- 차로수 별 자전거 횡단도 카운트/비율

- 차로수별 보행자 신호등 유무 카운트/비율

- 차로수별 음향 신호기 설치 유무 카운트/비율

#### 화면 출력

1.상관도 수치

2.비율 수치

3~5 카운트 비율



In [131]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=5, suppress=True)

def my_split(s):
    block_start = False
    start_index = 0
    ret_list=[]
    for i, c in enumerate(s):
        if block_start==False:
            if c==',':
                ret_list.append(s[start_index:i])
                start_index=i+1
            elif c=='"':
                block_start=True
                start_index = i
        else:
            if c=='"':
                block_start=False
    if s[-1]!=',':
        ret_list.append(s[start_index:])
    return ret_list

def check_splite(list_data):
    t = set()
    for e in list_data:
        t.add(len(e))
    return len(t)

In [124]:
def np_data_from_data_go_kr_csv(filename):
    t = []
    with open (filename, encoding = 'cp949') as f:
        for line in f:
            t.append(my_split(line[:-1]))
        if check_splite(t) != 1:
            return None
        else:
            return np.array(t)
        
def print_index_title(np_data):
    for e in enumerate(np_data[0]):
        print(e)


In [178]:
def target1 (data):
    sub_data = np_data[1:,[13,17]]
    # 0 을 ''값으로 변환
    sub_data[sub_data == '0'] = ''
    # '' 값 제거
    filter1 = sub_data[:,1] != '' #and (sub_data[:,1] != '0')
    sub_data_f = sub_data[filter1].astype(np.float64)
    
#     _,axe = plt.subplots()
#     axe.scatter(sub_data_f[:,0], sub_data_f[:,1])
    
    filter2 = sub_data_f[:,0] < 100
    sub_data_f2 = sub_data_f[filter2]
    
#     axe.scatter(sub_data_f2[:,0], sub_data_f2[:,1])
    
    return np.corrcoef(sub_data_f2[:,0], sub_data_f2[:,1])[0,1]
#     print(np.unique(sub_data_f[:,0]))
#     print(np.unique(sub_data_f[:,1]))    
    
    
# target1(np_data)

In [125]:
def target2(data):
    sub_data = np_data[1:,7]
    val, cnt = np.unique(sub_data, return_counts=True)
#     print(val,cnt)
    
# target2(np_data)

[' ' 'N' 'Y'] [15910 29476  4614]


In [164]:
def target3(data):
    sub_data = np_data[1:,[11,7]]
#     print(np.unique(sub_data[:,0]))
#     print(np.unique(sub_data[:,1]))
    t = []
    for e in np.unique(sub_data[:,0]):
        filter1 = sub_data[:,0] == e
        sub_data_f =  sub_data[filter1]
        sub_data_f_y = sub_data_f[sub_data_f[:, 1] == 'Y']
        sub_data_f_n = sub_data_f[sub_data_f[:, 1] == 'N']
#         print(e, len(sub_data_f_y), len(sub_data_f_n))
#         print(np.unique(sub_data_f[:,1], return_counts= True))
#         print(len(sub_data_f_y) / len(sub_data_f_n))
        yes_count = len(sub_data_f_y)
        no_count = len(sub_data_f_n)
        yes_no_count = yes_count + no_count
        if yes_no_count == 0:
            yes_no_count = 1
        t.append((e, yes_count, no_count, yes_count / yes_no_count))
    t = np.array(t).astype(np.float64)
    t = np.array(sorted(t, key = lambda x: x[0]))
    return t
    
# target3(np_data)

array([[    0.     ,     0.     ,     2.     ,     0.     ],
       [    1.     ,   423.     ,  6166.     ,     0.0642 ],
       [    2.     ,   859.     , 12472.     ,     0.06444],
       [    3.     ,   489.     ,  2055.     ,     0.19222],
       [    4.     ,  1002.     ,  4662.     ,     0.17691],
       [    5.     ,   525.     ,  1573.     ,     0.25024],
       [    6.     ,   593.     ,  1460.     ,     0.28885],
       [    7.     ,   371.     ,   584.     ,     0.38848],
       [    8.     ,   166.     ,   334.     ,     0.332  ],
       [    9.     ,   125.     ,   123.     ,     0.50403],
       [   10.     ,    39.     ,    37.     ,     0.51316],
       [   11.     ,    12.     ,     6.     ,     0.66667],
       [   12.     ,     7.     ,     2.     ,     0.77778],
       [   13.     ,     3.     ,     0.     ,     1.     ],
       [   15.     ,     0.     ,     0.     ,     0.     ]])

In [173]:
def target4(data):
    sub_data = np_data[1:,[11,7]]
    sub_data[sub_data == 'n'] = 'N'
    sub_data[sub_data == 'y'] = 'Y'
#     print(np.unique(sub_data[:,0]))
#     print(np.unique(sub_data[:,1]))
    t = []
    for e in np.unique(sub_data[:,0]):
        filter1 = sub_data[:,0] == e
        sub_data_f =  sub_data[filter1]
        sub_data_f_y = sub_data_f[sub_data_f[:, 1] == 'Y']
        sub_data_f_n = sub_data_f[sub_data_f[:, 1] == 'N']
#         print(e, len(sub_data_f_y), len(sub_data_f_n))
#         print(np.unique(sub_data_f[:,1], return_counts= True))
#         print(len(sub_data_f_y) / len(sub_data_f_n))
        yes_count = len(sub_data_f_y)
        no_count = len(sub_data_f_n)
        yes_no_count = yes_count + no_count
        if yes_no_count == 0:
            yes_no_count = 1
        t.append((e, yes_count, no_count, yes_count / yes_no_count))
    t = np.array(t).astype(np.float64)
    t = np.array(sorted(t, key = lambda x: x[0]))
    return t
    
# target4(np_data)

array([[    0.     ,     0.     ,     2.     ,     0.     ],
       [    1.     ,   423.     ,  6166.     ,     0.0642 ],
       [    2.     ,   859.     , 12472.     ,     0.06444],
       [    3.     ,   489.     ,  2055.     ,     0.19222],
       [    4.     ,  1002.     ,  4662.     ,     0.17691],
       [    5.     ,   525.     ,  1573.     ,     0.25024],
       [    6.     ,   593.     ,  1460.     ,     0.28885],
       [    7.     ,   371.     ,   584.     ,     0.38848],
       [    8.     ,   166.     ,   334.     ,     0.332  ],
       [    9.     ,   125.     ,   123.     ,     0.50403],
       [   10.     ,    39.     ,    37.     ,     0.51316],
       [   11.     ,    12.     ,     6.     ,     0.66667],
       [   12.     ,     7.     ,     2.     ,     0.77778],
       [   13.     ,     3.     ,     0.     ,     1.     ],
       [   15.     ,     0.     ,     0.     ,     0.     ]])

In [174]:
def target5(data):
    sub_data = np_data[1:,[11,16]]
    sub_data[sub_data == 'n'] = 'N'
    sub_data[sub_data == 'y'] = 'Y'
#     print(np.unique(sub_data[:,0]))
#     print(np.unique(sub_data[:,1]))
    t = []
    for e in np.unique(sub_data[:,0]):
        filter1 = sub_data[:,0] == e
        sub_data_f =  sub_data[filter1]
        sub_data_f_y = sub_data_f[sub_data_f[:, 1] == 'Y']
        sub_data_f_n = sub_data_f[sub_data_f[:, 1] == 'N']
#         print(e, len(sub_data_f_y), len(sub_data_f_n))
#         print(np.unique(sub_data_f[:,1], return_counts= True))
#         print(len(sub_data_f_y) / len(sub_data_f_n))
        yes_count = len(sub_data_f_y)
        no_count = len(sub_data_f_n)
        yes_no_count = yes_count + no_count
        if yes_no_count == 0:
            yes_no_count = 1
        t.append((e, yes_count, no_count, yes_count / yes_no_count))
    t = np.array(t).astype(np.float64)
    t = np.array(sorted(t, key = lambda x: x[0]))
    return t
    
# target5(np_data)

array([[   0.     ,    2.     ,    0.     ,    1.     ],
       [   1.     ,   64.     , 3480.     ,    0.01806],
       [   2.     ,  582.     , 6873.     ,    0.07807],
       [   3.     ,  363.     , 1489.     ,    0.196  ],
       [   4.     ,  890.     , 2590.     ,    0.25575],
       [   5.     ,  571.     , 1006.     ,    0.36208],
       [   6.     ,  471.     ,  692.     ,    0.40499],
       [   7.     ,  300.     ,  384.     ,    0.4386 ],
       [   8.     ,  183.     ,  171.     ,    0.51695],
       [   9.     ,   81.     ,   95.     ,    0.46023],
       [  10.     ,   10.     ,   10.     ,    0.5    ],
       [  11.     ,    2.     ,    2.     ,    0.5    ],
       [  12.     ,    0.     ,    0.     ,    0.     ],
       [  13.     ,    0.     ,    0.     ,    0.     ],
       [  15.     ,    0.     ,    0.     ,    0.     ]])

In [6]:

if __name__ == '__main__':
    np_data = np_data_from_data_go_kr_csv('xing.csv')
    print(target1(np_data))
    print(target2(np_data))
    print(target3(np_data))
    print(target4(np_data))
    print(target5(np_data))
    
    
#     print_index_title(np_data)



NameError: name 'np_data_from_data_go_kr_csv' is not defined