In [6]:
import numpy as np

In [9]:
a1 = np.array([1,2,3,4,5]) #list랑 같이 생겼지만 출력시 콤마가 안찍힌다.
print([1,2,3,4,5])
print(a1)
print(type(a1))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
a2 = np.arange(10)
print(a2)

#100아래에 있는 3의 배수
a3 = np.arange(0,100,3)
print(a3)
#1에서부터 10아래 숫자 0.5씩 증가하는 숫자 step = 0.5 (실수 기입가능)
a4 = np.arange(1.3,10,0.5)
print(a4)
#python list에서는 step에 실수 기입 못함
#lista = [i for i in range(1,10,0.3)]

[0 1 2 3 4 5 6 7 8 9]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
[1.3 1.8 2.3 2.8 3.3 3.8 4.3 4.8 5.3 5.8 6.3 6.8 7.3 7.8 8.3 8.8 9.3 9.8]


In [26]:
a5 = np.linspace(0,10,2) #0~10까지 양쪽 포함에서 숫자를 n개 달라
print(a5)

[ 0. 10.]


In [32]:
a6 = np.zeros(5)# 0으로 채워줌
print(a6)
a7 = np.ones(5) # 1로 채워줌
print(a7)
#데이터 타입 변환
a6 = np.ones(5, dtype=np.int64)
print(a6)
a6.astype(np.float64)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]


array([1., 1., 1., 1., 1.])

In [37]:
lista = [1,2,3,1.4,4.5]
b1 = np.array(lista)
print(b1)

listb = [1,2,'abc','def']
b2 = np.array(listb)
print(b2)
#b2.astype(np.int64)

[1.  2.  3.  1.4 4.5]
['1' '2' 'abc' 'def']


In [43]:
print(a7.dtype)
print(a7.ndim) # 몇차원 배열인지.
print(a7.shape) # 이 array의 모양
print(a7.size) # array안에 모든 숫자

print(a7.itemsize) #바이트 사이즈
print(a7.data)

float64
1
(5,)
5
8


In [52]:
a10 = np.arange(10, 100, 5)
print(a10)
#특정 인덱스
print(a10[0],a10[-1])
#스타트, 스탑
print(a10[0:3])
#스타트,스탑,스텝
print(a10[0:6:2])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
10 95
[10 15 20]
[10 20 30]


In [55]:
a10 = np.arange(10,100,5)
print(a10)
print(a10[[1,3,7]]) # 보고싶은 index번호

list10 = [x for x in range(10,100,5)]
print(list10)
# print(list10[[1,3,7]])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 45]
[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]


In [59]:
a10 = np.arange(10,100,5)
print(a10)
print(a10[a10 %  10 == 5]) #조건식을 넣을 수 있다

x = (a10 % 10 == 5) # -조건식 자체가 ndarray를 만듬
print(x)
print(x.shape)
print(a10.shape)
print(a10[x])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 35 45 55 65 75 85 95]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True]
(18,)
(18,)
[15 25 35 45 55 65 75 85 95]


In [72]:
lista = [x for x in range(3)]
listb = [x for x in range(10,15)]
print(lista)
print(listb)
print(lista + listb) # 리스트를 이어붙임
# print(lista - listb) #에러남

[0, 1, 2]
[10, 11, 12, 13, 14]
[0, 1, 2, 10, 11, 12, 13, 14]


In [73]:
a1 = np.arange(5)
a2 = np.arange(10,15)
print(a1,a2)
print('add:',a1 + a2) #같은 인덱스 끼리 더하기(계산)을 함 , 인덱스 개수가 차이나면 에러가 남
print('sub:',a1 - a2)
print('mul:',a1 * a2)
print('div:',a1 / a2)
print(a1 % a2)
print(np.concatenate((a1,a2))) #list + list 랑 같음

[0 1 2 3 4] [10 11 12 13 14]
add: [10 12 14 16 18]
sub: [-10 -10 -10 -10 -10]
mul: [ 0 11 24 39 56]
div: [0.         0.09090909 0.16666667 0.23076923 0.28571429]
[0 1 2 3 4]
[ 0  1  2  3  4 10 11 12 13 14]
